extends: airbnb
settings:
  import/resolver: webpack
env:
  browser: true
parser: babel-eslint
rules:
  no-nested-ternary: 1
  linebreak-style: 0
  no-param-reassign: 0
  react/prefer-stateless-function: 1
  react/jsx-filename-extension: 0
  react/no-multi-comp: 1
  react/destructuring-assignment: 1
  no-underscore-dangle: 1
  jsx-a11y/no-noninteractive-element-interactions: 1
  jsx-a11y/no-static-element-interactions: 1
  jsx-a11y/click-events-have-key-events: 1
